name: Docker build and push
on:
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: markusmueller
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get short Git commit SHA
        id: vars
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Containerfile
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.COMMIT_SHA }}
