name: goreleaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
      -
        name: Restore modified time
        uses: chetan/git-restore-mtime-action@v2
        with:
          working-directory: './internal/service/testdata'
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22 
      - 
        name: Test
        run: go test -v ./...
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

